version: '3.4'

networks:
  userapitesttask-back-network:
    driver: bridge

services:
  userapitesttask.api:
    container_name: userapitesttask.api
    image: ${DOCKER_REGISTRY-}userapitesttaskapi
    build:
      context: .
      dockerfile: src/UserApiTestTask.Api/Dockerfile
    ports:
      - 5000:80
    environment:
      - AppSettings__AllowedOrigin=http://localhost:8081
      - AppSettings__AdminPassword=Admin
      - ConnectionStrings__Db=Host=userapitesttask.db;Port=5432;Database=postgres;Username=postgres;Password=example
      - ConnectionStrings__Redis=userapitesttask.redis:6379
      - JwtConfig__AccessTokenLifeTime=600
    depends_on:
      - userapitesttask.db
      - userapitesttask.redis
    networks:
      - userapitesttask-back-network
    restart: on-failure

  userapitesttask.db:
    container_name: userapitesttask.db
    image: postgres:14
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - userapitesttask-back-network
    volumes:
      - ..\UserApiTestTask.Volumes\Postgres:/var/lib/postgresql/data
    restart: on-failure

  userapitesttask.redis:
    container_name: userapitesttask.redis
    image: redis
    ports:
      - 6381:6379
    networks:
      - userapitesttask-back-network
    restart: on-failure